import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  FormBuilder,
  FormGroup,
  Validators,
  ValidatorFn,
  AbstractControl,
  ValidationErrors,
} from '@angular/forms';
import { Router } from '@angular/router';
import { MenuService } from '../../../services/menu.service';
import { MenuItem, MenuOptionRequest } from '../../../interfaces/menu';

@Component({
  selector: 'app-menu-management',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule],
  templateUrl: './menu-management.component.html',
  styleUrls: ['./menu-management.component.scss'],
})
export class MenuManagementComponent implements OnInit {
  menuOptionForm: FormGroup;
  menuItems: MenuItem[] = [];
  menuOptionsFlat: any[] = [];
  selectedFile: File | null = null;
  uploadedImages: string[] = [];
  isLoading = false;
  isEditing = false;
  currentOptionId: number | null = null;
  hasChildItems = false;
  private routeAutoGenerated = false;

  constructor(
    private fb: FormBuilder,
    private menuService: MenuService,
    private router: Router
  ) {
    this.menuOptionForm = this.fb.group(
      {
        parentId: [0, Validators.required],
        title: ['', Validators.required],
        route: [''],
      },
      { validators: this.customValidators() }
    );
  }

  ngOnInit(): void {
    this.loadMenuItems();
    this.loadMenuOptionsFlat();

    // Listen for title changes to auto-generate route when images are present
    this.menuOptionForm.get('title')?.valueChanges.subscribe(() => {
      this.autoGenerateRoute();
    });

    // Listen for manual route changes to disable auto-generation
    this.menuOptionForm.get('route')?.valueChanges.subscribe((newValue) => {
      // If user manually types in the route field, disable auto-generation
      if (newValue && !this.routeAutoGenerated) {
        this.routeAutoGenerated = false;
      }
    });
  }

  // Custom validators for form
  customValidators(): ValidatorFn {
    return (group: AbstractControl): ValidationErrors | null => {
      const images = this.uploadedImages;
      const route = group.get('route')?.value;

      // If menu item has images
      if (images && images.length > 0) {
        // Route is required when images are present
        if (!route) {
          group.get('route')?.setErrors({ routeRequiredWithImages: true });
          return { routeRequiredWithImages: true };
        }

        // Check if this is an edit and the item has children
        if (this.isEditing && this.currentOptionId && this.hasChildItems) {
          return { cannotHaveImagesAndChildren: true };
        }
      }

      return null;
    };
  }

  loadMenuItems(): void {
    this.menuService.getMenuStructure().subscribe((response) => {
      this.menuItems = response.menuStructure.items;
    });
  }

  loadMenuOptionsFlat(): void {
    this.menuService.getMenuOptionsFlat().subscribe({
      next: (options) => {
        this.menuOptionsFlat = options;
        console.log('Opciones de menú cargadas en formato plano:', options);
      },
      error: (error) => {
        console.error(
          'Error al cargar opciones de menú en formato plano:',
          error
        );
      },
    });
  }

  // Get available parent options (only those without content images)
  get availableParentOptions() {
    return this.menuOptionsFlat.filter((option) => {
      // Exclude current option when editing to prevent circular reference
      if (this.isEditing && option.id === this.currentOptionId) {
        return false;
      }
      // Only include options without images
      return !option.images || option.images.length === 0;
    });
  }

  // Get parent title by parent ID
  getParentTitle(parentId: number): string {
    const parent = this.menuOptionsFlat.find(
      (option) => option.id === parentId
    );
    return parent ? parent.title : 'No encontrado';
  }

  // Convert title to kebab-case for route generation
  private titleToKebabCase(title: string): string {
    return (
      title
        .toLowerCase()
        .trim()
        // Handle Spanish accented characters
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '') // Remove diacritics
        .replace(/ñ/g, 'n') // Handle ñ specifically
        .replace(/[\s\-_]+/g, '-') // Replace spaces, hyphens, and underscores with single hyphen
        .replace(/[^\w\-]/g, '') // Remove special characters except hyphens
        .replace(/\-+/g, '-') // Replace multiple hyphens with single hyphen
        .replace(/^\-|\-$/g, '')
    ); // Remove leading/trailing hyphens
  }

  // Auto-generate route from title when images are added
  private autoGenerateRoute(): void {
    const titleValue = this.menuOptionForm.get('title')?.value;
    const routeValue = this.menuOptionForm.get('route')?.value;

    // Only auto-generate if:
    // 1. There are images
    // 2. Title exists and is not empty
    // 3. Route is empty OR was previously auto-generated
    if (this.uploadedImages.length > 0 && titleValue && titleValue.trim()) {
      const shouldRegenerate =
        !routeValue || routeValue.trim() === '' || this.routeAutoGenerated;

      if (shouldRegenerate) {
        const generatedRoute = '/' + this.titleToKebabCase(titleValue);
        this.menuOptionForm.patchValue({ route: generatedRoute });
        this.routeAutoGenerated = true;
      }
    }
  }

  // Check if the selected menu option has children
  checkForChildren(optionId: number): boolean {
    if (!optionId) return false;
    // Find any menu option that has this option as parent
    return this.menuOptionsFlat.some((option) => option.parentId === optionId);
  }

  // Seleccionar opción para editar
  selectOptionForEdit(option: any): void {
    this.isEditing = true;
    this.currentOptionId = option.id;
    this.hasChildItems = this.checkForChildren(option.id);

    // Rellenar el formulario con los datos de la opción seleccionada
    this.menuOptionForm.patchValue({
      parentId: option.parentId || 0,
      title: option.title,
      route: option.route || '',
    });

    // Set the uploaded images
    if (option.images && option.images.length > 0) {
      this.uploadedImages = [...option.images];
    } else {
      this.uploadedImages = [];
    }

    // Determine if the current route appears to be auto-generated
    if (option.route && option.title) {
      const expectedRoute = '/' + this.titleToKebabCase(option.title);
      this.routeAutoGenerated = option.route === expectedRoute;
    } else {
      this.routeAutoGenerated = false;
    }

    // Validate form after setting values
    this.menuOptionForm.updateValueAndValidity();
  }

  // Cancelar edición
  cancelEdit(): void {
    this.isEditing = false;
    this.currentOptionId = null;
    this.hasChildItems = false;
    this.resetForm();
  }

  // Eliminar opción de menú
  deleteOption(id: number): void {
    // Check if option has children
    if (this.checkForChildren(id)) {
      alert(
        'No se puede eliminar esta opción porque tiene elementos hijos. Elimine primero los elementos hijos.'
      );
      return;
    }

    if (
      confirm(
        '¿Está seguro de eliminar esta opción de menú? Esta acción no se puede deshacer.'
      )
    ) {
      this.isLoading = true;
      this.menuService.deleteMenuOption(id).subscribe({
        next: () => {
          this.isLoading = false;
          this.loadMenuItems();
          this.loadMenuOptionsFlat();
          alert('Opción de menú eliminada correctamente');
        },
        error: (error) => {
          this.isLoading = false;
          console.error('Error eliminando opción de menú:', error);
          alert('Error al eliminar la opción de menú');
        },
      });
    }
  }

  resetForm(): void {
    this.menuOptionForm.reset({
      parentId: 0,
      title: '',
      route: '',
    });
    this.uploadedImages = [];
    this.hasChildItems = false;
    this.routeAutoGenerated = false;
  }

  onFileSelected(event: any): void {
    if (event.target.files && event.target.files.length > 0) {
      this.selectedFile = event.target.files[0];
      this.uploadImage();
    }
  }

  uploadImage(): void {
    if (!this.selectedFile) return;

    this.isLoading = true;
    this.menuService.uploadMenuImage(this.selectedFile).subscribe({
      next: (response) => {
        this.isLoading = false;
        // Extract the URL from the response object
        const imageUrl = response.url;
        // Add the image URL to our list of uploaded images
        this.uploadedImages.push(imageUrl);
        // Clear the file input
        this.selectedFile = null;
        // Auto-generate route from title if needed
        this.autoGenerateRoute();
        // Validate form after adding image
        this.menuOptionForm.updateValueAndValidity();
      },
      error: (error) => {
        this.isLoading = false;
        console.error('Error uploading image:', error);
      },
    });
  }

  removeImage(index: number): void {
    this.uploadedImages.splice(index, 1);
    // Validate form after removing image
    this.menuOptionForm.updateValueAndValidity();
  }

  onSubmit(): void {
    if (this.menuOptionForm.valid) {
      // Check if item has images and has child items
      if (
        this.uploadedImages.length > 0 &&
        this.isEditing &&
        this.currentOptionId
      ) {
        const hasChildren = this.checkForChildren(this.currentOptionId);
        if (hasChildren) {
          alert(
            'No se puede guardar una opción con imágenes si tiene elementos hijos. Elimine las imágenes o los elementos hijos.'
          );
          return;
        }
      }

      const menuOption: MenuOptionRequest = {
        ...this.menuOptionForm.value,
        images:
          this.uploadedImages.length > 0 ? [...this.uploadedImages] : undefined,
      };

      this.isLoading = true;

      if (this.isEditing && this.currentOptionId) {
        // Actualizar opción existente
        this.menuService
          .updateMenuOption(this.currentOptionId, menuOption)
          .subscribe({
            next: () => {
              this.isLoading = false;
              this.isEditing = false;
              this.currentOptionId = null;
              this.resetForm();
              this.loadMenuItems();
              this.loadMenuOptionsFlat();
              alert('Opción de menú actualizada correctamente');
            },
            error: (error) => {
              this.isLoading = false;
              console.error('Error actualizando opción de menú:', error);
              alert('Error al actualizar la opción de menú');
            },
          });
      } else {
        // Crear nueva opción
        this.menuService.addMenuOption(menuOption).subscribe({
          next: () => {
            this.isLoading = false;
            this.resetForm();
            this.loadMenuItems();
            this.loadMenuOptionsFlat();
            alert('Opción de menú creada correctamente');
          },
          error: (error) => {
            this.isLoading = false;
            console.error('Error creating menu option:', error);
            alert('Error al crear la opción de menú');
          },
        });
      }
    } else {
      // Mark all fields as touched to show validation errors
      Object.keys(this.menuOptionForm.controls).forEach((key) => {
        const control = this.menuOptionForm.get(key);
        control?.markAsTouched();
      });

      // Show appropriate error message
      if (this.menuOptionForm.hasError('routeRequiredWithImages')) {
        alert('Cuando se añaden imágenes, la ruta es obligatoria.');
      } else if (this.menuOptionForm.hasError('cannotHaveImagesAndChildren')) {
        alert(
          'Una opción de menú no puede tener imágenes y elementos hijos al mismo tiempo.'
        );
      }
    }
  }
}
